name: Only Main

if: github.ref == 'refs/heads/main'

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: '배포할 브랜치 이름'
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest

# 입력받은 BRANCH, 기본 변수 GITHUB_REF_NAME, GITHUB_REF 값을 확인하기 위해 출력합니다.
    steps:
      - name: Check variables
        run: |
          echo "BRANCH: ${{ github.event.inputs.BRANCH }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_REF: ${{ github.ref }}"