name: Test

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: '배포할 브랜치 이름'
        required: true
        type: choice

jobs:
  test:
    runs-on: ubuntu-latest

# 입력받은 BRANCH, 기본 변수 GITHUB_REF_NAME, GITHUB_REF 값을 확인하기 위해 출력합니다.
    steps:
      - name: Check variables
        run: |
          echo "BRANCH: ${{ github.event.inputs.BRANCH }}"
          echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
          echo "GITHUB_REF: ${{ env.GITHUB_REF }}"
      
    